kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: traefik-ingress-controller
  namespace: kube-system
  labels:
    k8s-app: traefik-ingress-lb
spec:
  replicas: 1
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      k8s-app: traefik-ingress-lb
  strategy:
    # better for stateless services, no outage
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  template:
    metadata:
      labels:
        k8s-app: traefik-ingress-lb
        name: traefik-ingress-lb
    spec:
      serviceAccountName: traefik-ingress-controller
      terminationGracePeriodSeconds: 60
      volumes:
        - name: config
          configMap:
            name: traefik-conf
      containers:
        - image: traefik
          imagePullPolicy: Always
          name: traefik-ingress-lb
          volumeMounts:
            - mountPath: /config
              name: config
          ports:
            - name: api
              containerPort: 8181
            - name: http
              containerPort: 8182
            - name: admin
              containerPort: 8080
            - name: https
              containerPort: 8143
          securityContext:
            capabilities:
              drop:
                - ALL
              add:
                - NET_BIND_SERVICE
          args:
            - --api
            - --kubernetes
            - --configfile=/config/traefik.toml
          livenessProbe:
            httpGet:
              path: /ping
              port: 8182
            initialDelaySeconds: 3
            periodSeconds: 3
            timeoutSeconds: 1
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: traefik-conf
  namespace: kube-system
data:
  traefik.toml: |
    defaultEntryPoints = ["http","https"]
    debug = false
    logLevel = "INFO"

    [web]
      address = ":8080"

    [api]
      entryPoint = "api"
      dashboard = true

    [entryPoints]
      [entryPoints.api]
      address=":8181"
      [entryPoints.http]
      address = ":8182"
      compress = true
      [entryPoints.https]
      address = ":8143"
        [entryPoints.https.tls]

    [kubernetes]
      namespaces = ["default","kube-system","lupinemoon"]

    [ping]
    entryPoint = "http"
