kind: Service
apiVersion: v1
metadata:
  name: traefik-ingress-service
  namespace: kube-system
spec:
  selector:
    k8s-app: traefik-ingress-lb
  externalTrafficPolicy: Local
  ports:
    - protocol: TCP
      port: 8181
      name: api
    - protocol: TCP
      port: 8182
      name: http
    - protocol: TCP
      port: 8183
      targetPort: 8080
      name: admin
    - protocol: TCP
      port: 8143
      name: https
  type: LoadBalancer
